When receiving an unexpected verb, bad errors are generated
I was testing a very simple implementation of Restiq that simply
answered for "GET /", then I threw a "PUT /blah" at it, causing this
message:

    TypeError: Cannot read property 'path' of undefined
        at Restiq.mapRoute
        (/.../node_modules/restiq/lib/restiq.js:347:39)

Wrapping these two statements in an `if` statement solves the problem
and the mapRoute function shall still properly return `undefined` when
there is no route for that method.